Completed and tested dependency update bash script on Linux

diff --git a/gcmake-update-deps b/gcmake-update-deps
--- a/gcmake-update-deps
+++ b/gcmake-update-deps
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 if ! command -v git 2>/dev/null > /dev/null; then
 	echo "Unable to find 'git' on the system. Make sure git is installed."
 	exit
@@ -7,7 +9,7 @@ update_or_fix_single_repo() {
 	repo_dir="$1"
 	clean_only_mode=$2
 	dry_run=$3
-  dep_name=$(basename $(dirname $repo_dir))
+  dep_name="$(basename $(dirname $repo_dir))"
 
   if [[ -d "$repo_dir/.git" ]]; then
     cd "$repo_dir" || exit
@@ -17,12 +19,12 @@ update_or_fix_single_repo() {
         revision_name=$(git symbolic-ref --short -q HEAD)
         revision_type='branch'
 
-        if [[ -z "$revision_name" ]]
+        if [[ -z "$revision_name" ]]; then
           revision_name=$(git describe --tags --exact-match 2> /dev/null)
           revision_type='tag'
         fi
 
-        if [[ -z "$revision_name" ]]
+        if [[ -z "$revision_name" ]]; then
           revision_name=$(git rev-parse --short HEAD)
           revision_type='commit hash'
         fi
@@ -32,8 +34,8 @@ update_or_fix_single_repo() {
         if [[ $dry_run ]]; then
           echo "Would update $message_base"
         else
-          git checkout $revision_name 2>&1 > /dev/null
-          (git pull origin $revision_name 2>&1 > /dev/null && echo "Updated $message_base") || echo "Failed to update $message_base"
+          git checkout "$revision_name" 2>/dev/null > /dev/null
+          (git pull origin "$revision_name" 2>/dev/null > /dev/null && echo "Updated $message_base") || echo "Failed to update $message_base"
         fi
       fi
     else
@@ -43,6 +45,12 @@ update_or_fix_single_repo() {
         rm -r "$repo_dir" && echo "Removed invalid repository at $repo_dir"
       fi
     fi
+  elif [[ -z "$(ls -A $repo_dir)" ]]; then
+    if [[ $dry_run ]]; then
+      echo "Would remove invalid directory (maybe due to failed archive download?) at $repo_dir"
+    else
+      rm -r "$repo_dir" && echo "Removed invalid directory (maybe due to failed archive download?) at $repo_dir"
+    fi
   fi
 }
 
@@ -51,10 +59,10 @@ do_repo_updates() {
 	dry_run=$2
 	gcmake_dep_dir="$HOME/.gcmake/dep-cache"
 
-	for dep_dir in $gcmake_dep_dir/*; do
-    for repo_dir in $dep_dir; do
-      if [ -d $repo_container_dir ]; then
-        update_or_fix_single_repo "$repo_dir" $clean_only_mode $dry_run &
+	for dep_dir in "$gcmake_dep_dir"/*; do
+    for repo_dir in "$dep_dir"/*; do
+      if [ -d "$repo_dir" ]; then
+        update_or_fix_single_repo "$repo_dir" "$clean_only_mode" "$dry_run" &
       fi
     done
 	done
@@ -76,4 +84,4 @@ while getopts "cd" flags; do
 	esac
 done
 
-do_repo_updates $clean_only $dry_run
+do_repo_updates "$clean_only" "$dry_run"
